### ISSUE TITLE
It does not seem to work with instagram

### ISSUE THREAD

**Issue by roostaamir** [Fuzion24/JustTrustMe#27] opened 2017-06-18 19:51 UTC
I am trying to monitor instagram's traffic on my old galaxy s3 (using fiddler proxy on my PC) and it still won't show me the actual traffic?
Is something wrong?

**Comment by Fuzion24** [comment] 2017-06-19 13:28
dupe of #19

**Closed by Fuzion24** 2017-06-19 13:28 UTC
